branches:
  only:
    - master
language: objective-c
osx_image: xcode7
before_install:
  - gem install xcpretty --no-document -N
  - gem install cocoapods --no-document --pre --quiet
script:
  - pod install
  - pod lib lint ParseUI.podspec
  - pod lib lint --use-libraries ParseUI.podspec
  - set -o pipefail
  - xcodebuild -workspace ParseUI.xcworkspace -scheme 'ParseUI' -sdk iphonesimulator build | xcpretty -c
  - xcodebuild -workspace ParseUI.xcworkspace -scheme 'ParseUIDemo' -sdk iphonesimulator build | xcpretty -c
  - xcodebuild -workspace ParseUI.xcworkspace -scheme 'ParseUIDemo-Swift' -sdk iphonesimulator build | xcpretty -c
